# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ecfintools',
                'doc_host': 'https://vtecftwy.github.io',
                'git_url': 'https://github.com/vtecftwy/ecfintools',
                'lib_path': 'ecfintools'},
  'syms': {'ecfintools.core': {'ecfintools.core.foo': ('core.html#foo', 'ecfintools/core.py')}}}
