# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/myquantlab',
                'doc_host': 'https://vtecftwy.github.io',
                'git_url': 'https://github.com/vtecftwy/myquantlab',
                'lib_path': 'myquantlab'},
  'syms': { 'myquantlab.core': { 'myquantlab.core.load_test_df': ('core.html#load_test_df', 'myquantlab/core.py'),
                                 'myquantlab.core.safe_date': ('core.html#safe_date', 'myquantlab/core.py'),
                                 'myquantlab.core.time_slice_df': ('core.html#time_slice_df', 'myquantlab/core.py')},
            'myquantlab.dataAPI_legacy': {},
            'myquantlab.ohlc': { 'myquantlab.ohlc.autocorrelation_ohlcv': ('ohlcv.html#autocorrelation_ohlcv', 'myquantlab/ohlc.py'),
                                 'myquantlab.ohlc.candlestick_plot': ('ohlcv.html#candlestick_plot', 'myquantlab/ohlc.py'),
                                 'myquantlab.ohlc.resample_ohlcv': ('ohlcv.html#resample_ohlcv', 'myquantlab/ohlc.py')},
            'myquantlab.plotting': { 'myquantlab.plotting.hist_timeseries': ('plotting.html#hist_timeseries', 'myquantlab/plotting.py'),
                                     'myquantlab.plotting.normal_probability_plot': ( 'plotting.html#normal_probability_plot',
                                                                                      'myquantlab/plotting.py'),
                                     'myquantlab.plotting.plot_acfs': ('plotting.html#plot_acfs', 'myquantlab/plotting.py'),
                                     'myquantlab.plotting.plot_timeseries': ('plotting.html#plot_timeseries', 'myquantlab/plotting.py')}}}
